apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slackin.fullname" . }}
  labels:
    app: {{ include "slackin.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  slackApiToken: {{ .Values.slackApiToken | b64enc | quote }}
  googleCaptchaSecret: {{ .Values.googleCaptchaSecret | b64enc | quote }}
  googleCaptchaSiteKey: {{ .Values.googleCaptchaSiteKey | b64enc | quote }}
